# Generated by Django 5.1.3 on 2024-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=40)),
                (
                    "category_image",
                    models.ImageField(null=True, upload_to="category_image"),
                ),
            ],
        ),
    ]
