# Generated by Django 5.1.3 on 2024-12-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=40)),
                ("product_price", models.IntegerField()),
                (
                    "product_image",
                    models.ImageField(null=True, upload_to="product_image"),
                ),
                (
                    "brand_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maabees.brand",
                    ),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maabees.category",
                    ),
                ),
            ],
        ),
    ]
