# Generated by Django 5.1.3 on 2024-12-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0003_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="brand_name", new_name="brand_id",
        ),
        migrations.RenameField(
            model_name="product", old_name="category_name", new_name="category_id",
        ),
    ]
