# Generated by Django 5.1.3 on 2024-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0004_rename_brand_name_product_brand_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=40)),
                ("product_id", models.CharField(max_length=40)),
                ("brand_id", models.CharField(max_length=40)),
                ("product_name", models.CharField(max_length=40)),
                ("product_price", models.IntegerField()),
                (
                    "product_image",
                    models.ImageField(null=True, upload_to="whishlist_image"),
                ),
            ],
        ),
    ]
