# Generated by Django 5.1.3 on 2024-12-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0007_oder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=40)),
                ("mobile_no", models.IntegerField()),
                ("pin_code", models.IntegerField()),
                ("place", models.CharField(max_length=40)),
                ("district", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
            ],
        ),
    ]
