# Generated by Django 5.1.3 on 2024-12-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0008_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=40)),
                ("product_id", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=40)),
                ("date", models.DateField()),
            ],
        ),
    ]
