# Generated by Django 5.1.3 on 2024-12-09 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0009_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="date",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
    ]
