# Generated by Django 5.1.3 on 2024-12-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maabees", "0010_alter_feedback_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
