from django.urls import path
from . import views

urlpatterns=[
    path('',views.index),
    path('user-register/',views.user_register_view.as_view()),
    path('user-login/',views.user_login_view.as_view()),
    path('users-view/',views.users_view.as_view()),
    path('one-user-view/<int:id>',views.one_user_view.as_view()),
    path('user-update/<int:id>',views.user_update_view.as_view()),
    path('user-delete/<int:id>',views.user_delete_view.as_view()),
    path('brand-register/',views.brand_register_view.as_view()),
    path('brand-login/',views.brand_login_view.as_view()),
    path('brand-all-view/',views.brand_all_view.as_view()),
    path('brand-one-view/<int:id>',views.brand_one_view.as_view()),
    path('brand-update/<int:id>',views.brand_update_view.as_view()),
    path('brand-delete/<int:id>',views.brand_delete_view.as_view()),
    path('category-add/',views.category_add_view.as_view()),
    path('category-view/',views.category_view.as_view()),
    path('category-update/<int:id>',views.category_update_view.as_view()),
    path('category-delete/<int:id>',views.category_delete_view.as_view()),
    path('product-add/',views.product_add_view.as_view()),
    path('product-view/',views.product_view.as_view()),
    path('product-category_view/<int:category_id>',views.product_category_view.as_view()),
    path('product-brand-view/<int:brand_id>',views.product_brand_view.as_view()),
    path('product-update/<int:id>',views.product_update_view.as_view()),
    path('product-delete/<int:id>',views.product_delete_view.as_view()),
    path('product-search/',views.product_search_view.as_view()),
    path('whishlist-add/',views.whishlist_add_view.as_view()),
    path('whishlist-view/<int:user_id>',views.whishlist_view.as_view()),
    path('cart-add/',views.cart_add_view.as_view()),
    path('cart-view/<int:user_id>',views.cart_view.as_view()),
    path('cart-delete-based-on-product/<int:user_id>/<int:product_id>',views.cart_delete_based_on_product.as_view()),
    path('cart-delete/<int:user_id>',views.cart_delete_view.as_view()),
    path('oder-product/<int:user_id>',views.oder_product_view.as_view()),
    path('oder-view/<int:user_id>',views.oder_view.as_view()),
    path('address-add/<int:user_id>',views.address_add_view.as_view()),
    path('address-view/<int:user_id>',views.address_view.as_view()),
    path('address-update/<int:user_id>/<int:id>',views.address_update_view.as_view()),
    path('address-delete/<int:user_id>/<int:id>',views.address_delete_view.as_view()),
    path('feedback-add/',views.feedback_add_view.as_view()),
    path('feedback-view/<int:user_id>',views.feedback_view.as_view()),
    path('feedback-product-by-view/<int:product_id>',views.feedback_product_by_view.as_view()),
    path('feedback-delete/<int:user_id>/<int:id>',views.feedback_delete_view.as_view()),
    
    
]